from typing import Dict, List, Any, Optional
from argparse import Namespace

class CodebaseAnalysisViewerCLI:
    def __init__(self) -> None: ...
    def run(self) -> None: ...
    def _handle_analyze_command(self, args: Namespace) -> None: ...
    def _handle_compare_command(self, args: Namespace) -> None: ...
    def _run_interactive_mode(self) -> None: ...
    def _run_interactive_analyze(self) -> None: ...
    def _run_interactive_compare(self) -> None: ...

def main() -> None: ...

