import argparse
from typing import Any, List, Optional, Union

def create_parser() -> argparse.ArgumentParser: ...

class AnalysisViewerCLI:
    def __init__(self) -> None: ...
    def _setup_parser(self) -> argparse.ArgumentParser: ...
    def run(self, args: Optional[List[str]] = None) -> None: ...
    def _run_analyze(self, args: argparse.Namespace) -> None: ...
    def _run_compare(self, args: argparse.Namespace) -> None: ...
    def _run_interactive(self, args: argparse.Namespace) -> None: ...

