import argparse
from typing import Dict, List, Optional, Any, Union, Sequence

class AnalysisViewerCLI:
    def __init__(self) -> None: ...
    
    def _setup_parser(self) -> argparse.ArgumentParser: ...
    
    def run(self, args: Optional[Sequence[str]] = None) -> None: ...
    
    def _run_analyze(self, args: argparse.Namespace) -> None: ...
    
    def _run_compare(self, args: argparse.Namespace) -> None: ...
    
    def _run_interactive(self, args: argparse.Namespace) -> None: ...

def main() -> None: ...
