[project]
name = "pr-review-bot"
version = "0.1.0"
description = "PR review bot example for Codegen"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "modal>=0.73.25",
  "fastapi[standard]",
  "codegen>=0.52.19",
  "python-dotenv>=1.0.0",
]
