name: 'Run Benchmark'
description: 'Run pytest with benchmarking and process results'

inputs:
  test_path:
    description: 'Path to test files to run'
    required: true
  timeout:
    description: 'Timeout in minutes'
    required: false
    default: '10'
  suite_name:
    description: 'Name of the test suite'
    required: false
    default: ${{ github.job }}
  extra_args:
    description: 'Additional pytest arguments'
    required: false
    default: ''
  codecov_token:
    description: 'Token for uploading to codecov'
    required: false
  codspeed_token:
    description: 'Token for uploading to codspeed'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Make benchmark directory
      shell: bash
      run: mkdir -p build/test-results/test
    - name: Run benchmarks
      uses: CodSpeedHQ/action@v3
      with:
        token: ${{ inputs.codspeed_token }}
        run: uv run pytest ${{ inputs.test_path }} ${{ inputs.extra_args }} -o junit_suite_name=${{ inputs.suite_name }}
    - uses: ./.github/actions/report
      with:
        flag: no-flag
        codecov_token: ${{ inputs.codecov_token }}
