#!/usr/bin/env bash
# =============================================================================
# OmniNode AI — Claude Code Operator Integration
# =============================================================================
# Sets up OmniClaude as a Claude Code plugin with full ONEX integration:
#   - Deploys 5 Claude Code hooks
#   - Registers 54 agent definitions
#   - Enables 90+ skills
#   - Configures the Unix socket emit daemon
#   - Generates workspace CLAUDE.md
#
# Usage:
#   ./setup-claude-operator.sh --workspace /path/to/workspace [--env-file .env]
# =============================================================================
set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================
WORKSPACE=""
ENV_FILE=""
CLAUDE_CODE_DIR="$HOME/.claude"

while [[ $# -gt 0 ]]; do
  case $1 in
    --workspace) WORKSPACE="$2"; shift 2 ;;
    --env-file)  ENV_FILE="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$WORKSPACE" ]]; then
  echo "Error: --workspace required"
  exit 1
fi

OMNICLAUDE_DIR="${WORKSPACE}/omniclaude"
if [[ ! -d "$OMNICLAUDE_DIR" ]]; then
  echo "Error: omniclaude not found at $OMNICLAUDE_DIR"
  exit 1
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🤖 Setting up Claude Code Operator Integration${NC}"
echo ""

# =============================================================================
# Step 1: Source environment
# =============================================================================
if [[ -n "$ENV_FILE" && -f "$ENV_FILE" ]]; then
  echo -e "  ${GREEN}→${NC} Loading environment from $ENV_FILE"
  set -a
  source "$ENV_FILE"
  set +a
fi

# =============================================================================
# Step 2: Sync OmniClaude dependencies
# =============================================================================
echo -e "  ${GREEN}→${NC} Syncing OmniClaude dependencies..."
cd "$OMNICLAUDE_DIR"

if [[ -d "${WORKSPACE}/.venv" ]]; then
  source "${WORKSPACE}/.venv/bin/activate"
fi

# Use uv sync if available
if command -v uv &>/dev/null; then
  uv sync 2>/dev/null || echo "    (uv sync had warnings, continuing...)"
fi

# =============================================================================
# Step 3: Deploy hooks to Claude Code
# =============================================================================
echo -e "  ${GREEN}→${NC} Deploying Claude Code hooks..."

PLUGIN_SOURCE="${OMNICLAUDE_DIR}/plugins/onex"
PLUGIN_TARGET="${CLAUDE_CODE_DIR}/plugins/onex"

# Create Claude Code plugin directory
mkdir -p "$PLUGIN_TARGET"

# Copy hooks
if [[ -d "${PLUGIN_SOURCE}/hooks" ]]; then
  cp -r "${PLUGIN_SOURCE}/hooks" "${PLUGIN_TARGET}/"
  chmod +x "${PLUGIN_TARGET}/hooks/scripts/"*.sh 2>/dev/null || true
  echo -e "    ${GREEN}✓${NC} 5 hooks deployed (SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, SessionEnd)"
else
  echo -e "    ${YELLOW}⚠${NC} Hooks directory not found at ${PLUGIN_SOURCE}/hooks"
fi

# Copy agent configs
if [[ -d "${PLUGIN_SOURCE}/agents" ]]; then
  cp -r "${PLUGIN_SOURCE}/agents" "${PLUGIN_TARGET}/"
  AGENT_COUNT=$(find "${PLUGIN_TARGET}/agents" -name "*.yaml" -o -name "*.yml" 2>/dev/null | wc -l)
  echo -e "    ${GREEN}✓${NC} ${AGENT_COUNT} agent definitions deployed"
else
  echo -e "    ${YELLOW}⚠${NC} Agents directory not found"
fi

# Copy skills
if [[ -d "${PLUGIN_SOURCE}/skills" ]]; then
  cp -r "${PLUGIN_SOURCE}/skills" "${PLUGIN_TARGET}/"
  SKILL_COUNT=$(find "${PLUGIN_TARGET}/skills" -maxdepth 1 -type d 2>/dev/null | wc -l)
  echo -e "    ${GREEN}✓${NC} ${SKILL_COUNT} skills deployed"
else
  echo -e "    ${YELLOW}⚠${NC} Skills directory not found"
fi

# =============================================================================
# Step 4: Configure .env for OmniClaude
# =============================================================================
echo -e "  ${GREEN}→${NC} Configuring OmniClaude environment..."

OMNICLAUDE_ENV="${OMNICLAUDE_DIR}/.env"
cat > "$OMNICLAUDE_ENV" <<EOF
# OmniClaude Environment (auto-generated by setup-claude-operator.sh)
KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092}
KAFKA_ENVIRONMENT=${KAFKA_ENVIRONMENT:-dev}
KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-omniclaude-hooks}
USE_EVENT_ROUTING=${USE_EVENT_ROUTING:-true}

ENABLE_POSTGRES=${ENABLE_POSTGRES:-true}
OMNIBASE_INFRA_DB_URL=${OMNIBASE_INFRA_DB_URL:-postgresql://postgres:omninode-dev-password@localhost:5436/omnibase_infra}

ENABLE_QDRANT=${ENABLE_QDRANT:-true}
QDRANT_URL=${QDRANT_URL:-http://localhost:6333}
QDRANT_COLLECTION=${QDRANT_COLLECTION:-omninode_patterns}

INTELLIGENCE_API_URL=${INTELLIGENCE_API_URL:-http://localhost:8053}

ONEX_LOG_LEVEL=${ONEX_LOG_LEVEL:-INFO}
ONEX_ENVIRONMENT=${ONEX_ENVIRONMENT:-development}
EOF
echo -e "    ${GREEN}✓${NC} .env configured for Full ONEX tier"

# =============================================================================
# Step 5: Generate workspace CLAUDE.md
# =============================================================================
echo -e "  ${GREEN}→${NC} Generating workspace CLAUDE.md..."

cat > "${WORKSPACE}/CLAUDE.md" <<'CLAUDEMD'
# OmniNode AI — Claude Code Workspace

## Platform Overview

This workspace contains the complete OmniNode AI platform — an open-source system for
building production-grade AI agent systems with the ONEX four-node architecture.

## Available OmniClaude Skills (90+)

Invoke skills with `onex:<skill-name>` in your prompts. Key categories:

### Pipeline & Workflow
- `onex:ticket-work` — Contract-driven ticket execution with phases
- `onex:ticket-pipeline` — Autonomous per-ticket pipeline (work → review → PR → CI → merge)
- `onex:local-review` — Local code review loop (review/fix/commit cycles)
- `onex:ci-fix-pipeline` — Self-healing CI pipeline with 3-attempt retry
- `onex:pr-polish` — Full PR readiness (conflicts, review comments, CI failures)

### Code Review
- `onex:pr-review` — Comprehensive PR review with priority organization
- `onex:review-cycle` — Guided local code review with human checkpoints

### Architecture & Design
- `onex:brainstorming` — Refine ideas into designs through collaborative questioning
- `onex:writing-plans` — Create implementation plans with file paths and verification
- `onex:decision-store` — Record and conflict-check architectural decisions

### Testing & Debugging
- `onex:systematic-debugging` — Four-phase debugging (root cause → pattern → hypothesis → implement)
- `onex:test-driven-development` — TDD workflow
- `onex:root-cause-tracing` — Trace bugs backward through call stack

### Integration Health
- `onex:gap-analysis` — Cross-repo integration audit (Kafka drift, type mismatches)
- `onex:gap-cycle` — Full detect → fix → verify cycle
- `onex:golden-path-validate` — Execute golden path event chain tests

### Observability
- `onex:system-status` — Full system health monitoring
- `onex:onex-status` — Show integration tier, probe age, service reachability

## ONEX 4-Node Architecture

All nodes follow the pattern: Effect (I/O) → Compute (transform) → Reducer (aggregate) → Orchestrator (coordinate)

## Repository Map

| Directory | Package | Purpose |
|-----------|---------|---------|
| omnibase_spi/ | omnibase-spi | Protocol interfaces (180+) |
| omnibase_core/ | omnibase-core | Pydantic models, DI container, validation |
| omnibase_infra/ | omnibase-infra | Kafka + PostgreSQL adapters |
| omniintelligence/ | omninode-intelligence | 21 intelligence nodes |
| omnimemory/ | omninode-memory | Semantic memory & retrieval |
| omniclaude/ | omninode-claude | Claude Code plugin (this integration) |
| omnidash/ | omnidash | Real-time React dashboard |
| onex_change_control/ | onex-change-control | Schema governance |

## Infrastructure

- **PostgreSQL**: localhost:5436 (4 databases)
- **Kafka/Redpanda**: localhost:19092 (22+ topics)
- **Qdrant**: localhost:6333 (5 collections)
- **Valkey**: localhost:16379 (cache)
- **Dashboard**: http://localhost:3000
- **Redpanda Console**: http://localhost:8080

## Integration Tier

Auto-detected at every SessionStart. Current setup supports **FULL_ONEX** tier:
- ✅ 90+ skills, 54 agents, all hooks
- ✅ Kafka event routing and telemetry
- ✅ Context enrichment from Qdrant
- ✅ Semantic memory retrieval
- ✅ Pattern compliance enforcement
CLAUDEMD

echo -e "    ${GREEN}✓${NC} CLAUDE.md generated at ${WORKSPACE}/CLAUDE.md"

# =============================================================================
# Step 6: Test emit daemon connectivity
# =============================================================================
echo -e "  ${GREEN}→${NC} Testing emit daemon setup..."

EMIT_WRAPPER="${OMNICLAUDE_DIR}/plugins/onex/hooks/lib/emit_client_wrapper.py"
if [[ -f "$EMIT_WRAPPER" ]]; then
  python "$EMIT_WRAPPER" status --json 2>/dev/null && \
    echo -e "    ${GREEN}✓${NC} Emit daemon reachable" || \
    echo -e "    ${YELLOW}⚠${NC} Emit daemon not running (will start at next SessionStart)"
else
  echo -e "    ${YELLOW}⚠${NC} Emit client wrapper not found (hooks may start daemon on first use)"
fi

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  🤖 Claude Code Operator Integration Complete       ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}║  Hooks:    5 (SessionStart → SessionEnd)             ║${NC}"
echo -e "${GREEN}║  Agents:   54 specialized routing definitions        ║${NC}"
echo -e "${GREEN}║  Skills:   90+ reusable workflows                    ║${NC}"
echo -e "${GREEN}║  Tier:     FULL_ONEX (auto-detected)                 ║${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}║  To activate in Claude Code:                         ║${NC}"
echo -e "${GREEN}║    /deploy-local-plugin                              ║${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"

