# PR Static Analysis Configuration

# Global configuration options
global:
  # Maximum number of issues to report per file
  max_issues_per_file: 10

  # Maximum number of issues to report per rule
  max_issues_per_rule: 20

  # Whether to include code snippets in the report
  include_code_snippets: true

  # Whether to include fix suggestions in the report
  include_fix_suggestions: true

# Rule-specific configuration options
rules:
  # Code integrity rules
  syntax-error:
    enabled: true
    severity: error

  code-smell:
    enabled: true
    severity: warning
    max_function_length: 50
    max_nesting_depth: 3
    ignore_magic_numbers: [-1, 0, 1, 2, 100]
    min_duplicate_lines: 5

  # Parameter validation rules
  unused-parameter:
    enabled: true
    severity: warning

  # Implementation validation rules
  missing-edge-case:
    enabled: true
    severity: warning

# List of explicitly enabled rules
enabled_rules:
  - syntax-error
  - code-smell
  - unused-parameter
  - missing-edge-case

# List of explicitly disabled rules
disabled_rules: []
