import os
import json
import logging
import time
from typing import Dict, List, Optional, Any

class PlanningManager:
    """Manager for project planning and task tracking."""
    
    def __init__(self, github_manager):
        """Initialize the planning manager."""
        self.github_manager = github_manager
        self.logger = logging.getLogger(__name__)
        self.plans = {}
    
    def create_plan(self, project_name: str, requirements: str, plan_text: str) -> Dict[str, Any]:
        """Create a new project plan.
        
        Args:
            project_name: Name of the project
            requirements: Project requirements
            plan_text: Plan text generated by the planning agent
            
        Returns:
            Dictionary with plan details
        """
        try:
            # Create a unique plan ID
            plan_id = f"plan_{int(time.time())}"
            
            # Parse the plan text to extract features and tasks
            features = self._extract_features_from_plan(plan_text)
            
            # Create the plan structure
            plan = {
                "id": plan_id,
                "project_name": project_name,
                "requirements": requirements,
                "plan_text": plan_text,
                "features": features,
                "status": "planning",
                "created_at": time.time(),
                "updated_at": time.time()
            }
            
            # Store the plan
            self.plans[plan_id] = plan
            
            return plan
        except Exception as e:
            self.logger.error(f"Error creating plan: {e}")
            return {"error": str(e)}
    
    def _extract_features_from_plan(self, plan_text: str) -> List[Dict[str, Any]]:
        """Extract features from the plan text.
        
        Args:
            plan_text: The plan text to parse
            
        Returns:
            List of feature dictionaries
        """
        features = []
        
        # Simple parsing logic - in a real implementation, this would be more robust
        # and potentially use the AI to extract structured data
        lines = plan_text.split("\n")
        current_feature = None
        
        for line in lines:
            line = line.strip()
            
            # Look for feature headings
            if line.startswith("## ") or line.startswith("# Feature:"):
                if current_feature:
                    features.append(current_feature)
                
                feature_name = line.split(":", 1)[1].strip() if ":" in line else line.lstrip("#").strip()
                current_feature = {
                    "name": feature_name,
                    "description": "",
                    "tasks": [],
                    "status": "not_started"
                }
            
            # Look for tasks
            elif line.startswith("- [ ]") or line.startswith("* [ ]") or line.startswith("- Task:"):
                if current_feature:
                    task_text = line.replace("- [ ]", "").replace("* [ ]", "").replace("- Task:", "").strip()
                    current_feature["tasks"].append({
                        "description": task_text,
                        "status": "not_started"
                    })
            
            # Add to description
            elif current_feature and not line.startswith("#") and line:
                if not current_feature["description"]:
                    current_feature["description"] = line
                else:
                    current_feature["description"] += "\n" + line
        
        # Add the last feature if there is one
        if current_feature:
            features.append(current_feature)
        
        return features
    
    def get_plan(self, plan_id: str) -> Optional[Dict[str, Any]]:
        """Get a plan by ID.
        
        Args:
            plan_id: The plan ID
            
        Returns:
            The plan dictionary or None if not found
        """
        return self.plans.get(plan_id)
    
    def update_feature_status(self, plan_id: str, feature_name: str, status: str) -> bool:
        """Update the status of a feature in a plan.
        
        Args:
            plan_id: The plan ID
            feature_name: The name of the feature to update
            status: The new status
            
        Returns:
            True if successful, False otherwise
        """
        try:
            plan = self.plans.get(plan_id)
            if not plan:
                self.logger.warning(f"Plan not found: {plan_id}")
                return False
            
            # Find the feature
            for feature in plan["features"]:
                if feature["name"] == feature_name:
                    feature["status"] = status
                    plan["updated_at"] = time.time()
                    return True
            
            self.logger.warning(f"Feature not found in plan: {feature_name}")
            return False
        except Exception as e:
            self.logger.error(f"Error updating feature status: {e}")
            return False
    
    def update_task_status(self, plan_id: str, feature_name: str, task_index: int, status: str) -> bool:
        """Update the status of a task in a feature.
        
        Args:
            plan_id: The plan ID
            feature_name: The name of the feature containing the task
            task_index: The index of the task in the feature's tasks list
            status: The new status
            
        Returns:
            True if successful, False otherwise
        """
        try:
            plan = self.plans.get(plan_id)
            if not plan:
                self.logger.warning(f"Plan not found: {plan_id}")
                return False
            
            # Find the feature
            for feature in plan["features"]:
                if feature["name"] == feature_name:
                    if 0 <= task_index < len(feature["tasks"]):
                        feature["tasks"][task_index]["status"] = status
                        plan["updated_at"] = time.time()
                        return True
                    else:
                        self.logger.warning(f"Task index out of range: {task_index}")
                        return False
            
            self.logger.warning(f"Feature not found in plan: {feature_name}")
            return False
        except Exception as e:
            self.logger.error(f"Error updating task status: {e}")
            return False
    
    def create_github_issues_for_plan(self, plan_id: str, repo_name: Optional[str] = None) -> Dict[str, Any]:
        """Create GitHub issues for all features in a plan.
        
        Args:
            plan_id: The plan ID
            repo_name: Optional repository name (uses default if not provided)
            
        Returns:
            Dictionary with results
        """
        try:
            plan = self.plans.get(plan_id)
            if not plan:
                self.logger.warning(f"Plan not found: {plan_id}")
                return {"error": "Plan not found"}
            
            results = {
                "plan_id": plan_id,
                "features": []
            }
            
            for feature in plan["features"]:
                feature_name = feature["name"]
                
                # Create issue title and body
                title = f"Feature: {feature_name}"
                body = f"# {feature_name}\n\n{feature['description']}\n\n## Tasks\n"
                
                for task in feature["tasks"]:
                    body += f"- [ ] {task['description']}\n"
                
                # Create the issue
                # In a real implementation, you would use the GitHub API to create the issue
                # and store the issue ID in the feature data
                
                # For now, we'll just log it
                self.logger.info(f"Would create GitHub issue for feature: {feature_name}")
                
                results["features"].append({
                    "name": feature_name,
                    "issue_created": True
                })
            
            return results
        except Exception as e:
            self.logger.error(f"Error creating GitHub issues: {e}")
            return {"error": str(e)}
    
    def generate_progress_report(self, plan_id: str) -> str:
        """Generate a progress report for a plan.
        
        Args:
            plan_id: The plan ID
            
        Returns:
            Markdown-formatted progress report
        """
        try:
            plan = self.plans.get(plan_id)
            if not plan:
                return "Plan not found"
            
            # Calculate progress statistics
            total_features = len(plan["features"])
            completed_features = sum(1 for f in plan["features"] if f["status"] == "completed")
            
            total_tasks = sum(len(f["tasks"]) for f in plan["features"])
            completed_tasks = sum(sum(1 for t in f["tasks"] if t["status"] == "completed") for f in plan["features"])
            
            feature_progress = (completed_features / total_features) * 100 if total_features > 0 else 0
            task_progress = (completed_tasks / total_tasks) * 100 if total_tasks > 0 else 0
            
            # Generate the report
            report = f"""# Progress Report: {plan['project_name']}

## Overall Progress
- Features: {completed_features}/{total_features} ({feature_progress:.1f}%)
- Tasks: {completed_tasks}/{total_tasks} ({task_progress:.1f}%)

## Feature Status
"""
            
            for feature in plan["features"]:
                feature_tasks = len(feature["tasks"])
                completed_feature_tasks = sum(1 for t in feature["tasks"] if t["status"] == "completed")
                feature_task_progress = (completed_feature_tasks / feature_tasks) * 100 if feature_tasks > 0 else 0
                
                status_emoji = "✅" if feature["status"] == "completed" else "🔄" if feature["status"] == "in_progress" else "⏳"
                
                report += f"""
### {status_emoji} {feature['name']}
- Status: {feature['status']}
- Progress: {completed_feature_tasks}/{feature_tasks} tasks ({feature_task_progress:.1f}%)
"""
            
            return report
        except Exception as e:
            self.logger.error(f"Error generating progress report: {e}")
            return f"Error generating progress report: {e}"
