#!/usr/bin/env bash
# =============================================================================
# OmniNode AI — Full Stack Deployment Script
# =============================================================================
# Single-command deployment of the entire OmniNode AI platform:
#   8 repositories, infrastructure, Python services, React dashboard,
#   and Claude Code operator integration.
#
# Usage:
#   ./deploy.sh              # Full deployment
#   ./deploy.sh --infra-only # Infrastructure only (Docker services)
#   ./deploy.sh --python-only # Python environment only (skip infra/frontend)
#   ./deploy.sh --skip-clone  # Skip repo cloning (repos already present)
#   ./deploy.sh --skip-infra  # Skip Docker infrastructure
#   ./deploy.sh --help        # Show help
#
# Prerequisites:
#   - Docker & Docker Compose v2.20+
#   - Python 3.12+
#   - uv (Python package manager)
#   - Node.js 20+ & npm
#   - git
#
# Author: Generated by Codegen for the OmniNode AI ecosystem
# =============================================================================
set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="${OMNINODE_WORKSPACE:-$SCRIPT_DIR/workspace}"
VENV_DIR="${WORKSPACE}/.venv"
LOG_FILE="${SCRIPT_DIR}/deploy.log"
GITHUB_ORG="OmniNode-ai"

# Repository list in dependency order
PYTHON_REPOS=(omnibase_spi omnibase_core omnibase_infra omniintelligence omnimemory omniclaude onex_change_control)
ALL_REPOS=("${PYTHON_REPOS[@]}" omnidash)

# Package names for editable installs (must match pyproject.toml 'name' field)
declare -A PKG_NAMES=(
  [omnibase_spi]="omnibase-spi"
  [omnibase_core]="omnibase-core"
  [omnibase_infra]="omnibase-infra"
  [omniintelligence]="omninode-intelligence"
  [omnimemory]="omninode-memory"
  [omniclaude]="omninode-claude"
  [onex_change_control]="onex-change-control"
)

# Python import names for verification
declare -A IMPORT_NAMES=(
  [omnibase_spi]="omnibase_spi"
  [omnibase_core]="omnibase_core"
  [omnibase_infra]="omnibase_infra"
  [omniintelligence]="omniintelligence"
  [omnimemory]="omnimemory"
  [omniclaude]="omniclaude"
)

# =============================================================================
# Colors & Logging
# =============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()    { echo -e "${GREEN}[✓]${NC} $1"; echo "[INFO] $(date +%H:%M:%S) $1" >> "$LOG_FILE"; }
log_warn()    { echo -e "${YELLOW}[⚠]${NC} $1"; echo "[WARN] $(date +%H:%M:%S) $1" >> "$LOG_FILE"; }
log_error()   { echo -e "${RED}[✗]${NC} $1"; echo "[ERROR] $(date +%H:%M:%S) $1" >> "$LOG_FILE"; }
log_step()    { echo -e "\n${BOLD}${CYAN}═══ $1 ═══${NC}"; echo "[STEP] $(date +%H:%M:%S) $1" >> "$LOG_FILE"; }
log_substep() { echo -e "  ${BLUE}→${NC} $1"; echo "[SUB] $(date +%H:%M:%S) $1" >> "$LOG_FILE"; }

# =============================================================================
# CLI Argument Parsing
# =============================================================================
INFRA_ONLY=false
PYTHON_ONLY=false
SKIP_CLONE=false
SKIP_INFRA=false
SKIP_FRONTEND=false
SKIP_CLAUDE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --infra-only)   INFRA_ONLY=true; shift ;;
    --python-only)  PYTHON_ONLY=true; SKIP_INFRA=true; SKIP_FRONTEND=true; shift ;;
    --skip-clone)   SKIP_CLONE=true; shift ;;
    --skip-infra)   SKIP_INFRA=true; shift ;;
    --skip-frontend) SKIP_FRONTEND=true; shift ;;
    --skip-claude)  SKIP_CLAUDE=true; shift ;;
    --workspace)    WORKSPACE="$2"; VENV_DIR="${WORKSPACE}/.venv"; shift 2 ;;
    --help|-h)
      echo "OmniNode AI Full Stack Deployment"
      echo ""
      echo "Usage: ./deploy.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --infra-only      Deploy infrastructure only (Docker services)"
      echo "  --python-only     Set up Python environment only"
      echo "  --skip-clone      Skip repository cloning"
      echo "  --skip-infra      Skip Docker infrastructure startup"
      echo "  --skip-frontend   Skip OmniDash frontend build"
      echo "  --skip-claude     Skip Claude Code operator setup"
      echo "  --workspace DIR   Set workspace directory (default: ./workspace)"
      echo "  --help            Show this help"
      exit 0
      ;;
    *) log_error "Unknown option: $1"; exit 1 ;;
  esac
done

# =============================================================================
# Banner
# =============================================================================
echo -e "${BOLD}"
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║              🧠  OmniNode AI — Full Stack Deploy  🧠           ║"
echo "║                                                                ║"
echo "║  8 Repositories • 54 Agents • 90+ Skills • 21 Intelligence    ║"
echo "║  Nodes • Kafka Event Bus • Semantic Memory • Live Dashboard   ║"
echo "║                                                                ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Initialize log
echo "=== OmniNode Deploy $(date) ===" > "$LOG_FILE"

# =============================================================================
# Step 0: Prerequisites Check
# =============================================================================
log_step "Step 0/8: Checking Prerequisites"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    local ver
    ver=$($2 2>/dev/null | head -1)
    log_substep "$1: ${GREEN}$ver${NC}"
    return 0
  else
    log_error "$1 not found. $3"
    return 1
  fi
}

PREREQS_OK=true
check_cmd docker "docker --version" "Install: https://docs.docker.com/get-docker/" || PREREQS_OK=false
check_cmd python3 "python3 --version" "Install Python 3.12+: https://python.org" || PREREQS_OK=false
check_cmd git "git --version" "Install: apt install git" || PREREQS_OK=false

# Check uv
if command -v uv &>/dev/null; then
  log_substep "uv: ${GREEN}$(uv --version 2>/dev/null)${NC}"
else
  log_warn "uv not found — installing..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  log_info "uv installed: $(uv --version)"
fi

# Check Node.js
if command -v node &>/dev/null; then
  log_substep "node: ${GREEN}$(node --version)${NC}"
else
  log_warn "Node.js not found — will skip frontend build"
  SKIP_FRONTEND=true
fi

# Check Docker Compose
if docker compose version &>/dev/null; then
  COMPOSE_VER=$(docker compose version --short 2>/dev/null)
  log_substep "docker compose: ${GREEN}v${COMPOSE_VER}${NC}"
else
  log_error "Docker Compose v2 not found"
  PREREQS_OK=false
fi

# Check Python version (need 3.12+)
PYTHON_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "0.0")
if [[ "$(echo "$PYTHON_VER" | cut -d. -f1)" -ge 3 && "$(echo "$PYTHON_VER" | cut -d. -f2)" -ge 12 ]]; then
  log_substep "Python version: ${GREEN}$PYTHON_VER ✓${NC}"
else
  log_error "Python 3.12+ required (found $PYTHON_VER)"
  PREREQS_OK=false
fi

if [[ "$PREREQS_OK" != "true" ]]; then
  log_error "Prerequisites check failed. Please install missing dependencies."
  exit 1
fi
log_info "All prerequisites satisfied"

# =============================================================================
# Step 1: Clone Repositories
# =============================================================================
log_step "Step 1/8: Cloning Repositories"

mkdir -p "$WORKSPACE"

if [[ "$SKIP_CLONE" == "true" ]]; then
  log_warn "Skipping clone (--skip-clone)"
else
  for repo in "${ALL_REPOS[@]}"; do
    if [[ -d "${WORKSPACE}/${repo}" ]]; then
      log_substep "${repo}: already exists, pulling latest..."
      (cd "${WORKSPACE}/${repo}" && git pull --ff-only 2>/dev/null || true)
    else
      log_substep "Cloning ${repo}..."
      git clone --depth 1 "https://github.com/${GITHUB_ORG}/${repo}.git" "${WORKSPACE}/${repo}" 2>&1 | tail -1
    fi
  done
  log_info "All ${#ALL_REPOS[@]} repositories cloned"
fi

if [[ "$INFRA_ONLY" == "true" ]]; then
  # Jump straight to infrastructure
  :
fi

# =============================================================================
# Step 2: Environment Configuration
# =============================================================================
log_step "Step 2/8: Environment Configuration"

ENV_FILE="${SCRIPT_DIR}/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  log_substep "Creating .env from template..."
  cp "${SCRIPT_DIR}/.env.example" "$ENV_FILE"
  # Generate a random password for dev
  DEV_PASSWORD=$(openssl rand -hex 16 2>/dev/null || echo "omninode-dev-$(date +%s)")
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "s/omninode-dev-password/$DEV_PASSWORD/g" "$ENV_FILE"
  else
    sed -i "s/omninode-dev-password/$DEV_PASSWORD/g" "$ENV_FILE"
  fi
  log_info ".env created with generated password"
else
  log_substep ".env already exists, using existing configuration"
fi

# Source environment
set -a
source "$ENV_FILE"
set +a
log_info "Environment loaded"

# =============================================================================
# Step 3: Docker Infrastructure
# =============================================================================
log_step "Step 3/8: Starting Docker Infrastructure"

if [[ "$SKIP_INFRA" == "true" ]]; then
  log_warn "Skipping infrastructure (--skip-infra)"
else
  # Make init script executable
  chmod +x "${SCRIPT_DIR}/config/postgres-init.sh"

  log_substep "Starting PostgreSQL, Redpanda, Qdrant, Valkey..."
  cd "$SCRIPT_DIR"
  docker compose up -d postgres redpanda qdrant valkey 2>&1 | tail -5

  # Wait for services to be healthy
  log_substep "Waiting for services to become healthy..."
  TIMEOUT=120
  ELAPSED=0
  while [[ $ELAPSED -lt $TIMEOUT ]]; do
    PG_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' omninode-postgres 2>/dev/null || echo "unknown")
    RP_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' omninode-redpanda 2>/dev/null || echo "unknown")
    QD_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' omninode-qdrant 2>/dev/null || echo "unknown")

    if [[ "$PG_HEALTHY" == "healthy" && "$RP_HEALTHY" == "healthy" && "$QD_HEALTHY" == "healthy" ]]; then
      break
    fi

    printf "\r  Waiting... PG=%s RP=%s QD=%s (%ds/%ds)" "$PG_HEALTHY" "$RP_HEALTHY" "$QD_HEALTHY" "$ELAPSED" "$TIMEOUT"
    sleep 3
    ELAPSED=$((ELAPSED + 3))
  done
  echo ""

  if [[ $ELAPSED -ge $TIMEOUT ]]; then
    log_warn "Some services may not be fully healthy yet (timeout after ${TIMEOUT}s)"
  else
    log_info "All infrastructure services healthy"
  fi

  # Start Redpanda Console (optional monitoring)
  log_substep "Starting Redpanda Console (monitoring UI)..."
  docker compose up -d redpanda-console 2>&1 | tail -1 || true

  # Create Kafka topics
  log_substep "Creating Kafka topics..."
  bash "${SCRIPT_DIR}/config/create-kafka-topics.sh" || log_warn "Topic creation had warnings (may already exist)"

  # Create Qdrant collections
  log_substep "Creating Qdrant collections..."
  bash "${SCRIPT_DIR}/config/create-qdrant-collections.sh" || log_warn "Qdrant collection setup had warnings"

  log_info "Infrastructure ready"
  echo -e "  ${BLUE}PostgreSQL:${NC}     localhost:${POSTGRES_PORT:-5436}"
  echo -e "  ${BLUE}Kafka:${NC}          localhost:19092"
  echo -e "  ${BLUE}Qdrant:${NC}         localhost:${QDRANT_HTTP_PORT:-6333}"
  echo -e "  ${BLUE}Valkey:${NC}         localhost:${VALKEY_PORT:-16379}"
  echo -e "  ${BLUE}Redpanda UI:${NC}    http://localhost:${REDPANDA_CONSOLE_PORT:-8080}"
fi

if [[ "$INFRA_ONLY" == "true" ]]; then
  log_info "Infrastructure-only deployment complete!"
  exit 0
fi

# =============================================================================
# Step 4: Python Virtual Environment
# =============================================================================
log_step "Step 4/8: Python Environment Setup"

if [[ -d "$VENV_DIR" ]]; then
  log_substep "Virtual environment exists, reusing..."
else
  log_substep "Creating virtual environment with Python 3.12..."
  uv venv "$VENV_DIR" --python 3.12 2>/dev/null || python3 -m venv "$VENV_DIR"
fi

# Activate
source "${VENV_DIR}/bin/activate"
log_substep "Activated: $(python --version) at $(which python)"

# Upgrade pip
uv pip install --upgrade pip setuptools wheel 2>/dev/null || pip install --upgrade pip setuptools wheel

# =============================================================================
# Step 5: Install Python Packages (Layered Editable Installs)
# =============================================================================
log_step "Step 5/8: Installing Python Packages (Dependency Order)"

echo -e "  ${CYAN}Install order: SPI → Core → Infra → Intelligence → Memory → Claude → ChangeControl${NC}"

install_package() {
  local repo=$1
  local pkg_name=${PKG_NAMES[$repo]}
  local repo_path="${WORKSPACE}/${repo}"

  if [[ ! -d "$repo_path" ]]; then
    log_error "Repository not found: $repo_path"
    return 1
  fi

  log_substep "Installing ${BOLD}${pkg_name}${NC} from ${repo}..."

  cd "$repo_path"

  # Install with uv pip (handles editable installs well)
  if uv pip install -e "." --no-deps 2>/dev/null; then
    log_substep "  ${GREEN}✓${NC} ${pkg_name} installed (no-deps)"
  else
    log_warn "  uv pip failed for ${pkg_name}, trying pip..."
    pip install -e "." --no-deps 2>/dev/null || {
      log_error "  Failed to install ${pkg_name}"
      return 1
    }
  fi
  return 0
}

# Install external dependencies first (from PyPI)
log_substep "Installing shared external dependencies..."
uv pip install \
  "pydantic>=2.12.5,<3.0.0" \
  "pydantic-settings>=2.6.0,<3.0.0" \
  "pyyaml>=6.0.2" \
  "typing-extensions>=4.5.0" \
  "dependency-injector>=4.48.3" \
  "deepdiff>=8.0.0" \
  "click>=8.3.1" \
  "cryptography>=46.0.3" \
  "jsonschema>=4.25.1" \
  "httpx>=0.27.0" \
  "blake3>=1.0.8" \
  "ruamel-yaml>=0.18.0" \
  "confluent-kafka>=2.12.0,<3.0.0" \
  "tenacity>=8.2.0" \
  "watchdog>=6.0.0" \
  "cachetools>=5.0.0" \
  "tiktoken>=0.5.0" \
  "fastapi>=0.120.1" \
  "uvicorn[standard]>=0.32.0" \
  "python-dotenv>=1.0.0" \
  "asyncpg>=0.29.0" \
  "psycopg2-binary>=2.9.10" \
  "mcp>=1.8.0,<2.0.0" \
  2>/dev/null || log_warn "Some dependencies may have version conflicts"

# Install in dependency order
for repo in "${PYTHON_REPOS[@]}"; do
  install_package "$repo" || log_warn "Warning: ${repo} installation incomplete"
done

# Now install with full deps to resolve any remaining
log_substep "Resolving remaining dependencies..."
for repo in "${PYTHON_REPOS[@]}"; do
  repo_path="${WORKSPACE}/${repo}"
  if [[ -d "$repo_path" ]]; then
    cd "$repo_path"
    uv pip install -e "." 2>/dev/null || pip install -e "." 2>/dev/null || true
  fi
done

# Verify imports
log_substep "Verifying Python imports..."
IMPORT_OK=true
for repo in "${!IMPORT_NAMES[@]}"; do
  import_name="${IMPORT_NAMES[$repo]}"
  if python -c "import ${import_name}" 2>/dev/null; then
    log_substep "  ${GREEN}✓${NC} import ${import_name}"
  else
    log_warn "  ${YELLOW}✗${NC} import ${import_name} failed"
    IMPORT_OK=false
  fi
done

if [[ "$IMPORT_OK" == "true" ]]; then
  log_info "All Python packages installed and importable"
else
  log_warn "Some packages could not be imported — check dependency versions"
fi

# =============================================================================
# Step 6: OmniDash Frontend
# =============================================================================
log_step "Step 6/8: Building OmniDash Frontend"

if [[ "$SKIP_FRONTEND" == "true" ]]; then
  log_warn "Skipping frontend (--skip-frontend or Node.js not found)"
else
  DASH_DIR="${WORKSPACE}/omnidash"
  if [[ -d "$DASH_DIR" ]]; then
    cd "$DASH_DIR"
    log_substep "Installing npm dependencies..."
    npm install 2>&1 | tail -3

    # Copy env
    if [[ ! -f ".env" ]]; then
      cp .env.example .env 2>/dev/null || true
      # Patch with our values
      cat >> .env <<EOF
PORT=${OMNIDASH_PORT:-3000}
OMNIDASH_ANALYTICS_DB_URL=${OMNIDASH_ANALYTICS_DB_URL}
KAFKA_BROKERS=${KAFKA_BOOTSTRAP_SERVERS}
KAFKA_CLIENT_ID=omnidash-dashboard
KAFKA_CONSUMER_GROUP=omnidash-consumers-v2
ENABLE_REAL_TIME_EVENTS=true
EOF
    fi

    log_substep "Building production bundle..."
    npm run build 2>&1 | tail -5 || log_warn "Build had warnings"
    log_info "OmniDash built successfully"
  else
    log_warn "OmniDash directory not found at $DASH_DIR"
  fi
fi

# =============================================================================
# Step 7: Claude Code Operator Integration
# =============================================================================
log_step "Step 7/8: Claude Code Operator Setup"

if [[ "$SKIP_CLAUDE" == "true" ]]; then
  log_warn "Skipping Claude Code setup (--skip-claude)"
else
  bash "${SCRIPT_DIR}/scripts/setup-claude-operator.sh" \
    --workspace "$WORKSPACE" \
    --env-file "$ENV_FILE" \
    2>&1 || log_warn "Claude Code setup had warnings"
fi

# =============================================================================
# Step 8: Start Services
# =============================================================================
log_step "Step 8/8: Starting Services"

# Create a services launcher script
cat > "${WORKSPACE}/start-services.sh" <<'LAUNCHER'
#!/usr/bin/env bash
# Start all OmniNode services
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"

echo "🚀 Starting OmniNode services..."

# Start Intelligence API (background)
if [ -d "${SCRIPT_DIR}/omniintelligence" ]; then
  echo "  → Starting Intelligence API on :8053..."
  cd "${SCRIPT_DIR}/omniintelligence"
  uvicorn omniintelligence.api:app --host 0.0.0.0 --port 8053 &
  echo $! > /tmp/omninode-intelligence.pid
fi

# Start OmniDash (background)
if [ -d "${SCRIPT_DIR}/omnidash" ]; then
  echo "  → Starting OmniDash on :3000..."
  cd "${SCRIPT_DIR}/omnidash"
  PORT=3000 npm start &
  echo $! > /tmp/omninode-dash.pid
fi

echo ""
echo "✅ Services started!"
echo "  Intelligence API: http://localhost:8053"
echo "  OmniDash:         http://localhost:3000"
echo "  Redpanda Console: http://localhost:8080"
echo ""
echo "To stop: kill \$(cat /tmp/omninode-*.pid)"
LAUNCHER
chmod +x "${WORKSPACE}/start-services.sh"

log_info "Service launcher created at: ${WORKSPACE}/start-services.sh"
log_substep "Run it with: ${WORKSPACE}/start-services.sh"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${BOLD}"
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                  🎉 DEPLOYMENT COMPLETE 🎉                     ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  Infrastructure:                                               ║"
echo "║    PostgreSQL .... localhost:${POSTGRES_PORT:-5436}                          ║"
echo "║    Kafka ......... localhost:19092                              ║"
echo "║    Qdrant ........ localhost:${QDRANT_HTTP_PORT:-6333}                          ║"
echo "║    Valkey ........ localhost:${VALKEY_PORT:-16379}                         ║"
echo "║    Redpanda UI ... http://localhost:${REDPANDA_CONSOLE_PORT:-8080}                   ║"
echo "║                                                                ║"
echo "║  Services:                                                     ║"
echo "║    Intelligence .. http://localhost:8053                        ║"
echo "║    OmniDash ..... http://localhost:3000                         ║"
echo "║                                                                ║"
echo "║  Python Environment:                                           ║"
echo "║    source ${VENV_DIR}/bin/activate               ║"
echo "║                                                                ║"
echo "║  Claude Code:                                                  ║"
echo "║    Agents: 54 │ Skills: 90+ │ Hooks: 5                        ║"
echo "║    Tier: FULL_ONEX (auto-detected)                             ║"
echo "║                                                                ║"
echo "║  Next Steps:                                                   ║"
echo "║    1. Start services: ${WORKSPACE}/start-services.sh           ║"
echo "║    2. Open dashboard: http://localhost:3000                     ║"
echo "║    3. In Claude Code: /deploy-local-plugin                     ║"
echo "║    4. Validate: ./validate.sh                                  ║"
echo "║                                                                ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

log_info "Full deploy log: $LOG_FILE"

