"""
ROMA Integration Layer

Integration layer for ROMA (Recursive-Open-Meta-Agent) that serves as the
meta-orchestrator for hierarchical task decomposition and agent coordination.

ROMA provides:
- Direct user interaction and natural language processing
- Hierarchical task decomposition and delegation
- Context aggregation from child agents
- Result validation and synthesis
- Dynamic agent spawning and coordination

This integration connects ROMA with:
- Codegen core library for operational foundation
- Z.AI substrate for intelligence processing
- High-value agent services (Claude + RepoMaster)
- Selective service integration based on task requirements
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List
from datetime import datetime
from dataclasses import dataclass
from enum import Enum

from .zai_substrate import ZAISubstrate, AgentRequest, ReasoningMode

logger = logging.getLogger(__name__)


class TaskComplexity(Enum):
    """Task complexity levels for ROMA processing."""
    SIMPLE = "simple"      # Single agent, straightforward execution
    MODERATE = "moderate"  # Multiple steps, single agent
    COMPLEX = "complex"    # Multiple agents, coordination required
    ADVANCED = "advanced"  # Hierarchical decomposition, recursive processing


@dataclass
class ROMATask:
    """Task structure for ROMA processing."""
    task_id: str
    description: str
    complexity: TaskComplexity
    parent_task_id: Optional[str] = None
    subtasks: List[str] = None
    assigned_agents: List[str] = None
    context: Dict[str, Any] = None
    priority: str = "normal"
    deadline: Optional[datetime] = None


@dataclass
class ExecutionPlan:
    """Execution plan generated by ROMA."""
    plan_id: str
    root_task: ROMATask
    task_hierarchy: Dict[str, ROMATask]
    execution_order: List[str]
    agent_assignments: Dict[str, str]
    estimated_duration: float
    resource_requirements: Dict[str, Any]


class ROMAIntegration:
    """
    ROMA meta-orchestrator integration for hierarchical task coordination.
    
    This class provides the interface between user requests and the ROMA
    meta-agent system, handling task decomposition, agent coordination,
    and result synthesis.
    """
    
    def __init__(
        self,
        zai_substrate: Optional[ZAISubstrate] = None,
        enable_recursive_processing: bool = True,
        max_task_depth: int = 5
    ):
        """
        Initialize ROMA integration.
        
        Args:
            zai_substrate: Z.AI substrate for intelligence processing
            enable_recursive_processing: Enable recursive task decomposition
            max_task_depth: Maximum depth for task hierarchy
        """
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")
        
        # Z.AI substrate for ROMA intelligence
        self.zai_substrate = zai_substrate or ZAISubstrate()
        
        # ROMA configuration
        self.enable_recursive_processing = enable_recursive_processing
        self.max_task_depth = max_task_depth
        
        # Task management
        self.active_tasks: Dict[str, ROMATask] = {}
        self.execution_plans: Dict[str, ExecutionPlan] = {}
        self.task_results: Dict[str, Dict[str, Any]] = {}
        
        # Agent coordination
        self.available_agents = {
            "codegen_claude": {
                "capabilities": ["development", "code_generation", "pr_creation", "analysis"],
                "load": 0.0,
                "status": "available"
            },
            "repomaster": {
                "capabilities": ["code_analysis", "repository_insights", "validation", "quality_assessment"],
                "load": 0.0,
                "status": "available"
            }
        }
        
        self.logger.info("ROMA Integration initialized")
    
    async def initialize(self) -> None:
        """Initialize ROMA integration and register with Z.AI substrate."""
        try:
            # Register ROMA as a meta-agent with Z.AI substrate
            await self.zai_substrate._register_agent("roma_meta_orchestrator")
            
            self.logger.info("ROMA Integration initialization complete")
            
        except Exception as e:
            self.logger.error(f"Failed to initialize ROMA integration: {e}")
            raise
    
    async def process_user_request(
        self, 
        user_message: str, 
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Process user request through ROMA meta-orchestration.
        
        This is the main entry point for user interactions, providing
        natural language processing and intelligent task decomposition.
        """
        try:
            # Analyze user request with ROMA intelligence
            analysis = await self._analyze_user_request(user_message, context)
            
            # Create root task from analysis
            root_task = await self._create_root_task(user_message, analysis, context)
            
            # Generate execution plan through hierarchical decomposition
            execution_plan = await self._generate_execution_plan(root_task)
            
            # Execute plan with agent coordination
            result = await self.execute_plan(execution_plan)
            
            return {
                "content": result.get("content", ""),
                "task_id": root_task.task_id,
                "execution_plan_id": execution_plan.plan_id,
                "agents_used": result.get("agents_used", []),
                "metadata": result.get("metadata", {}),
                "requires_followup": result.get("requires_followup", False),
                "suggested_actions": result.get("suggested_actions", [])
            }
            
        except Exception as e:
            self.logger.error(f"Error processing user request: {e}")
            return {
                "content": f"Error processing request: {str(e)}",
                "error": str(e),
                "requires_followup": True,
                "suggested_actions": ["Please try rephrasing your request"]
            }
    
    async def execute_plan(self, execution_plan: ExecutionPlan) -> Dict[str, Any]:
        """
        Execute a ROMA-generated execution plan.
        
        Coordinates multiple agents according to the hierarchical task structure
        and synthesizes results into a coherent response.
        """
        try:
            # Store execution plan
            self.execution_plans[execution_plan.plan_id] = execution_plan
            
            # Execute tasks in hierarchical order
            results = {}
            for task_id in execution_plan.execution_order:
                task = execution_plan.task_hierarchy[task_id]
                
                # Execute task with assigned agent
                agent_name = execution_plan.agent_assignments.get(task_id)
                if agent_name:
                    result = await self._execute_task_with_agent(task, agent_name)
                    results[task_id] = result
                    
                    # Store result for context in subsequent tasks
                    self.task_results[task_id] = result
            
            # Synthesize results through ROMA
            synthesized_result = await self._synthesize_results(execution_plan, results)
            
            return synthesized_result
            
        except Exception as e:
            self.logger.error(f"Error executing plan: {e}")
            return {
                "content": f"Error executing plan: {str(e)}",
                "error": str(e),
                "agents_used": [],
                "metadata": {"execution_plan_id": execution_plan.plan_id}
            }
    
    async def _analyze_user_request(
        self, 
        user_message: str, 
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Analyze user request to determine task complexity and requirements."""
        analysis_prompt = f"""
        As ROMA meta-orchestrator, analyze this user request for CI/CD operations:
        
        User Request: {user_message}
        Context: {context}
        
        Determine:
        1. Task complexity (simple, moderate, complex, advanced)
        2. Required capabilities and agents
        3. Potential subtasks and decomposition
        4. Estimated effort and timeline
        5. Dependencies and prerequisites
        6. Success criteria
        
        Provide structured analysis for task planning.
        """
        
        analysis_request = AgentRequest(
            agent_id="roma_meta_orchestrator",
            prompt=analysis_prompt,
            context=context,
            reasoning_mode=ReasoningMode.THINKING
        )
        
        response = await self.zai_substrate.process_agent_request(analysis_request)
        
        # Parse analysis (simplified for now - would use structured parsing)
        return {
            "complexity": self._determine_complexity(user_message),
            "required_capabilities": self._extract_capabilities(user_message),
            "estimated_subtasks": self._estimate_subtasks(user_message),
            "priority": context.get("priority", "normal"),
            "reasoning_trace": response.reasoning_trace
        }
    
    def _determine_complexity(self, message: str) -> TaskComplexity:
        """Determine task complexity based on message analysis."""
        message_lower = message.lower()
        
        # Advanced: Multiple systems, complex workflows
        if any(keyword in message_lower for keyword in [
            "deploy", "ci/cd", "pipeline", "orchestrate", "coordinate"
        ]):
            return TaskComplexity.ADVANCED
        
        # Complex: Multiple agents, coordination needed
        elif any(keyword in message_lower for keyword in [
            "analyze and fix", "review and deploy", "test and validate"
        ]):
            return TaskComplexity.COMPLEX
        
        # Moderate: Multiple steps, single agent
        elif any(keyword in message_lower for keyword in [
            "create and test", "build and validate", "generate and review"
        ]):
            return TaskComplexity.MODERATE
        
        # Simple: Single action, straightforward
        else:
            return TaskComplexity.SIMPLE
    
    def _extract_capabilities(self, message: str) -> List[str]:
        """Extract required capabilities from message."""
        capabilities = []
        message_lower = message.lower()
        
        if any(keyword in message_lower for keyword in ["code", "function", "class", "develop"]):
            capabilities.append("development")
        
        if any(keyword in message_lower for keyword in ["analyze", "review", "quality"]):
            capabilities.append("code_analysis")
        
        if any(keyword in message_lower for keyword in ["pr", "pull request", "merge"]):
            capabilities.append("pr_creation")
        
        if any(keyword in message_lower for keyword in ["test", "validate", "verify"]):
            capabilities.append("validation")
        
        return capabilities
    
    def _estimate_subtasks(self, message: str) -> int:
        """Estimate number of subtasks based on message complexity."""
        message_lower = message.lower()
        
        # Count action words and conjunctions
        action_words = ["create", "build", "test", "deploy", "analyze", "review", "fix", "update"]
        conjunctions = ["and", "then", "after", "before", "also"]
        
        action_count = sum(1 for word in action_words if word in message_lower)
        conjunction_count = sum(1 for word in conjunctions if word in message_lower)
        
        return max(1, action_count + conjunction_count)
    
    async def _create_root_task(
        self, 
        user_message: str, 
        analysis: Dict[str, Any], 
        context: Dict[str, Any]
    ) -> ROMATask:
        """Create root task from user request analysis."""
        task_id = f"task_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        return ROMATask(
            task_id=task_id,
            description=user_message,
            complexity=analysis["complexity"],
            context=context,
            priority=analysis.get("priority", "normal")
        )
    
    async def _generate_execution_plan(self, root_task: ROMATask) -> ExecutionPlan:
        """Generate hierarchical execution plan for the root task."""
        plan_id = f"plan_{root_task.task_id}"
        
        if root_task.complexity == TaskComplexity.SIMPLE:
            # Simple task - direct execution
            return ExecutionPlan(
                plan_id=plan_id,
                root_task=root_task,
                task_hierarchy={root_task.task_id: root_task},
                execution_order=[root_task.task_id],
                agent_assignments={root_task.task_id: self._select_best_agent(root_task)},
                estimated_duration=5.0,
                resource_requirements={"agents": 1, "complexity": "low"}
            )
        
        elif root_task.complexity in [TaskComplexity.MODERATE, TaskComplexity.COMPLEX]:
            # Decompose into subtasks
            subtasks = await self._decompose_task(root_task)
            
            task_hierarchy = {root_task.task_id: root_task}
            execution_order = []
            agent_assignments = {}
            
            for subtask in subtasks:
                task_hierarchy[subtask.task_id] = subtask
                execution_order.append(subtask.task_id)
                agent_assignments[subtask.task_id] = self._select_best_agent(subtask)
            
            return ExecutionPlan(
                plan_id=plan_id,
                root_task=root_task,
                task_hierarchy=task_hierarchy,
                execution_order=execution_order,
                agent_assignments=agent_assignments,
                estimated_duration=len(subtasks) * 3.0,
                resource_requirements={"agents": len(subtasks), "complexity": "medium"}
            )
        
        else:  # ADVANCED
            # Recursive hierarchical decomposition
            return await self._generate_advanced_plan(root_task, plan_id)
    
    async def _decompose_task(self, task: ROMATask) -> List[ROMATask]:
        """Decompose a task into subtasks using ROMA intelligence."""
        decomposition_prompt = f"""
        As ROMA meta-orchestrator, decompose this task into executable subtasks:
        
        Task: {task.description}
        Complexity: {task.complexity.value}
        Context: {task.context}
        
        Create a logical sequence of subtasks that can be executed by available agents.
        Each subtask should be specific and actionable.
        """
        
        decomposition_request = AgentRequest(
            agent_id="roma_meta_orchestrator",
            prompt=decomposition_prompt,
            context=task.context or {},
            reasoning_mode=ReasoningMode.THINKING
        )
        
        response = await self.zai_substrate.process_agent_request(decomposition_request)
        
        # Parse subtasks (simplified - would use structured parsing)
        subtasks = []
        subtask_descriptions = self._parse_subtasks_from_response(response.content)
        
        for i, description in enumerate(subtask_descriptions):
            subtask = ROMATask(
                task_id=f"{task.task_id}_sub_{i+1}",
                description=description,
                complexity=TaskComplexity.SIMPLE,
                parent_task_id=task.task_id,
                context=task.context,
                priority=task.priority
            )
            subtasks.append(subtask)
        
        return subtasks
    
    def _parse_subtasks_from_response(self, response_content: str) -> List[str]:
        """Parse subtasks from ROMA response (simplified implementation)."""
        # This would be more sophisticated in practice
        lines = response_content.split('\n')
        subtasks = []
        
        for line in lines:
            line = line.strip()
            if line and (line.startswith('-') or line.startswith('1.') or line.startswith('•')):
                # Clean up the line
                clean_line = line.lstrip('-1234567890.• ').strip()
                if clean_line:
                    subtasks.append(clean_line)
        
        return subtasks[:5]  # Limit to 5 subtasks for now
    
    async def _generate_advanced_plan(
        self, 
        root_task: ROMATask, 
        plan_id: str
    ) -> ExecutionPlan:
        """Generate advanced hierarchical execution plan with recursive decomposition."""
        # For now, treat as complex task
        # In full implementation, this would support deeper hierarchies
        return await self._generate_execution_plan(
            ROMATask(
                task_id=root_task.task_id,
                description=root_task.description,
                complexity=TaskComplexity.COMPLEX,
                context=root_task.context,
                priority=root_task.priority
            )
        )
    
    def _select_best_agent(self, task: ROMATask) -> str:
        """Select the best agent for a given task based on capabilities and load."""
        required_capabilities = self._extract_capabilities(task.description)
        
        best_agent = None
        best_score = 0.0
        
        for agent_name, agent_info in self.available_agents.items():
            # Calculate capability match score
            capability_matches = sum(
                1 for cap in required_capabilities 
                if cap in agent_info["capabilities"]
            )
            capability_score = capability_matches / max(len(required_capabilities), 1)
            
            # Factor in current load (prefer less loaded agents)
            load_score = 1.0 - agent_info["load"]
            
            # Combined score
            total_score = (capability_score * 0.7) + (load_score * 0.3)
            
            if total_score > best_score and agent_info["status"] == "available":
                best_score = total_score
                best_agent = agent_name
        
        return best_agent or "codegen_claude"  # Default fallback
    
    async def _execute_task_with_agent(
        self, 
        task: ROMATask, 
        agent_name: str
    ) -> Dict[str, Any]:
        """Execute a task with the specified agent."""
        # Create agent request with task context
        agent_request = AgentRequest(
            agent_id=agent_name,
            prompt=f"""
            Execute this CI/CD task:
            
            Task: {task.description}
            Context: {task.context}
            Priority: {task.priority}
            
            Provide detailed results and any follow-up recommendations.
            """,
            context=task.context or {},
            reasoning_mode=ReasoningMode.CONTEXTUAL
        )
        
        # Process through Z.AI substrate
        response = await self.zai_substrate.process_agent_request(agent_request)
        
        return {
            "content": response.content,
            "agent_used": agent_name,
            "confidence": response.confidence,
            "metadata": response.metadata,
            "processing_time": response.processing_time
        }
    
    async def _synthesize_results(
        self, 
        execution_plan: ExecutionPlan, 
        results: Dict[str, Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Synthesize results from multiple tasks into coherent response."""
        synthesis_prompt = f"""
        As ROMA meta-orchestrator, synthesize these task results into a coherent response:
        
        Original Request: {execution_plan.root_task.description}
        
        Task Results:
        {self._format_results_for_synthesis(results)}
        
        Provide:
        1. Summary of what was accomplished
        2. Key outcomes and deliverables
        3. Any issues or concerns
        4. Recommended next steps
        5. Overall success assessment
        """
        
        synthesis_request = AgentRequest(
            agent_id="roma_meta_orchestrator",
            prompt=synthesis_prompt,
            context=execution_plan.root_task.context or {},
            reasoning_mode=ReasoningMode.THINKING
        )
        
        response = await self.zai_substrate.process_agent_request(synthesis_request)
        
        # Compile final result
        agents_used = list(set(r.get("agent_used", "") for r in results.values()))
        total_processing_time = sum(r.get("processing_time", 0.0) for r in results.values())
        
        return {
            "content": response.content,
            "agents_used": agents_used,
            "metadata": {
                "execution_plan_id": execution_plan.plan_id,
                "tasks_completed": len(results),
                "total_processing_time": total_processing_time,
                "synthesis_confidence": response.confidence
            },
            "requires_followup": self._assess_followup_needed(results),
            "suggested_actions": self._extract_suggested_actions(response.content)
        }
    
    def _format_results_for_synthesis(self, results: Dict[str, Dict[str, Any]]) -> str:
        """Format task results for synthesis prompt."""
        formatted = []
        for task_id, result in results.items():
            formatted.append(f"Task {task_id}: {result.get('content', '')[:200]}...")
        return "\n".join(formatted)
    
    def _assess_followup_needed(self, results: Dict[str, Dict[str, Any]]) -> bool:
        """Assess if followup is needed based on task results."""
        # Check for errors or low confidence scores
        for result in results.values():
            if "error" in result.get("metadata", {}):
                return True
            if result.get("confidence", 1.0) < 0.7:
                return True
        return False
    
    def _extract_suggested_actions(self, synthesis_content: str) -> List[str]:
        """Extract suggested actions from synthesis content."""
        # Simple extraction - would be more sophisticated in practice
        actions = []
        lines = synthesis_content.split('\n')
        
        for line in lines:
            if 'recommend' in line.lower() or 'suggest' in line.lower():
                actions.append(line.strip())
        
        return actions[:3]  # Limit to 3 suggestions
    
    async def get_task_status(self, task_id: str) -> Optional[Dict[str, Any]]:
        """Get status of a specific task."""
        task = self.active_tasks.get(task_id)
        if not task:
            return None
        
        return {
            "task_id": task_id,
            "description": task.description,
            "complexity": task.complexity.value,
            "status": "completed" if task_id in self.task_results else "active",
            "result": self.task_results.get(task_id)
        }
    
    async def health_check(self) -> Dict[str, Any]:
        """Perform health check of ROMA integration."""
        return {
            "status": "healthy",
            "timestamp": datetime.now().isoformat(),
            "active_tasks": len(self.active_tasks),
            "execution_plans": len(self.execution_plans),
            "available_agents": len([
                agent for agent, info in self.available_agents.items()
                if info["status"] == "available"
            ]),
            "zai_substrate_status": await self.zai_substrate.health_check()
        }
    
    async def shutdown(self) -> None:
        """Gracefully shutdown ROMA integration."""
        self.logger.info("Shutting down ROMA Integration")
        
        # Clear active tasks and plans
        self.active_tasks.clear()
        self.execution_plans.clear()
        self.task_results.clear()
        
        self.logger.info("ROMA Integration shutdown complete")
