[project]
name = "github-checks"
version = "0.1.0"
description = "GitHub checks example for Codegen"
requires-python = ">=3.13"
dependencies = [
  "modal>=0.73.25",
  "fastapi[standard]",
  "codegen>=0.52.19",
  "python-dotenv>=1.0.0",
  "networkx>=3.0.0",
]
