[package]
name = "codegen-sdk-cst-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.7.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

[dev-dependencies]
serde_json = "1.0.138"
tree-sitter-python = "0.23.6"
