name: Mypy Checks

on:
  pull_request:
    branches:
      - "develop"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR number
        id: check_pr
        run: |
          if [[ "${{ github.event.pull_request.number }}" == "30" ]]; then
            echo "Skip mypy check for PR #30"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup environment
        if: steps.check_pr.outputs.skip != 'true'
        uses: ./.github/actions/setup-environment

      - name: Get changed files
        if: steps.check_pr.outputs.skip != 'true'
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1

      - name: Filter Python files
        if: steps.check_pr.outputs.skip != 'true'
        id: filter-python
        run: |
          python_files=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.py ]]; then
              python_files+=(\"${file}\")
            fi
          done
          echo "python_files=${python_files[*]}" >> $GITHUB_ENV

      - name: Add MyPy annotator
        if: steps.check_pr.outputs.skip != 'true'
        uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: Run mypy
        if: steps.check_pr.outputs.skip != 'true' && env.python_files != ''
        run: |
          echo "Running mypy on changed files: ${{ env.python_files }}"
          uv run mypy --no-pretty --show-absolute-path ${{ env.python_files }}
