name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  access-check:
    runs-on: ubuntu-latest
    # Skip the permission check for codegen-sh[bot]
    if: github.actor != 'codegen-sh[bot]'
    steps:
      - uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor || github.actor }}
          error-if-missing: true

  unit-tests:
    needs: access-check
    runs-on: ubuntu-latest-8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Test with pytest
        timeout-minutes: 5
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: |
          uv run pytest \
            -n auto \
            -o junit_suite_name="${{github.job}}" \
            tests/unit

      - uses: ./.github/actions/report
        with:
          flag: unit-tests
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  codemod-tests:
    needs: access-check
    # TODO: re-enable when this check is a develop required check
    if: false
    runs-on: ubuntu-latest-32
    strategy:
      matrix:
        size: [small, medium, large]
        sync_graph: [true, false]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos

      - name: Install yarn and pnpm
        run: |
          npm install -g yarn &
          npm install -g pnpm

      - name: Test with pytest
        timeout-minutes: 15
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: |
          uv run pytest \
            -n auto \
            -o junit_suite_name="${{github.job}}" \
            tests/integration/codemod/test_${{ matrix.size }}.py \
            -k "sync_graph_${{ matrix.sync_graph }}"

      - uses: ./.github/actions/report
        with:
          flag: codemod-tests-${{matrix.size}}-${{matrix.sync_graph}}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE

