name: Unit Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  benchmark-tests:
    runs-on: ubuntu-latest-16
    steps:
      - uses: actions/checkout@v4
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Run benchmark tests
        uses: ./.github/actions/run_benchmark
        with:
          test_path: tests/benchmark
          timeout: 5
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  unit-tests:
    # changing the following value will significantly affect github's cost. Be careful and consult with the team before changing it.
    runs-on: ubuntu-latest-32
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Run ATS and Tests
        uses: ./.github/actions/run_ats
        with:
          default_tests: "tests/unit"
          codecov_static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          collect_args: "--timeout 5"
          codecov_flags: unit-tests

  codemod-tests:
    # changing the following value will significantly affect github's cost. Be careful and consult with the team before changing it.
    runs-on: ubuntu-latest-32
    strategy:
      matrix:
        sync_graph: [ true, false ]
        size: [ small, large ]
        exclude:
          # Exclude large codemod tests when not needed
          - size: ${{(contains(github.event.pull_request.labels.*.name, 'big-codemod-tests') || github.event_name == 'push' || github.event_name == 'workflow_dispatch') && 'kevin' || 'large'}}
          - size: large
            sync_graph: true
    concurrency:
      group: ${{ github.workflow }}-${{github.ref}}-${{matrix.sync_graph}}-${{matrix.size}}-${{github.event_name == 'push'&& github.sha}}
      cancel-in-progress: true
    name: "Codemod tests ${{matrix.size}}: Sync Graph=${{matrix.sync_graph}}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos
      - name: Run ATS and Tests
        uses: ./.github/actions/run_ats
        with:
          default_tests: "tests/integration/codemod/test_codemods.py"
          codecov_static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          collect_args: "--size=${{matrix.size}} --sync-graph=${{matrix.sync_graph}}"
          ats_collect_args: "--size=${{matrix.size}},--sync-graph=${{matrix.sync_graph}},"
          codecov_flags: codemod-tests-${{matrix.size}}-${{matrix.sync_graph}}
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE

  parse-tests:
    # changing the following value will significantly affect github's cost. Be careful and consult with the team before changing it.
    runs-on: ubuntu-latest-32
    if: contains(github.event.pull_request.labels.*.name, 'parse-tests') || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: parse-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos
      - name: Install yarn and pnpm
        run: |
          npm install -g yarn &
          npm install -g pnpm
      - name: Run benchmark tests
        uses: ./.github/actions/run_benchmark
        with:
          test_path: tests/integration/codemod/test_parse.py
          timeout: 15
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify parse tests failure
        uses: slackapi/slack-github-action@v2.0.0
        if: failure() && github.event_name == 'push' && false
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Parse Tests Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Branch:* ${{ github.ref_name }}\n*Triggered by:* <${{ github.server_url }}/${{ github.actor }}|@${{ github.actor }}>\n\n*Details:*\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Failed at <!date^${{ github.event.head_commit.timestamp }}^{date_num} {time}|just now>"
                    }
                  ]
                }
              ]
            }

  integration-tests:
    runs-on: ubuntu-latest-16
    steps:
      - uses: actions/checkout@v4
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Run pytest
        uses: ./.github/actions/run_pytest
        with:
          test_path: tests/integration/codegen
          timeout: 5
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          collect_args: "--dist=loadgroup -n auto"
